CREATE TABLE register(
id SERIAL PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE CHECK (username != ''),
email VARCHAR(255) NOT NULL UNIQUE CHECK (email != ''),
password VARCHAR(255) NOT NULL CHECK (password != ''),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
